network:
  # ecg_model: resnet18
  ecg_model: fractal_ecg_encoder
  num_leads: 12
  ### this part does not control builder/trainer
  text_model: ncbi/MedCPT-Query-Encoder
  free_layers: 9 # set 12 to freeze all layer in bert
  feature_dim: 768

  projection_head:
    mlp_hidden_size: 256
    projection_size: 256
  ###

dataset:
  dataset_name: 'mimic'
  data_path: './' # add your image file path here

# params for trainer
trainer:
  batch_size: 512
  val_batch_size: 512
  checkpoint_interval: 50
  max_epochs: 50
  num_workers: 5

optimizer:
  params:
    lr: 2.0e-4
    weight_decay: 1.0e-5

# params for zeroshot eval
zeroshot:
  prompt_type: 'CKEPE'
  prompt_dict: '../zeroshot/CKEPE_prompt.json'
  batch_size: 512
  num_workers: 5
  meta_data_path: '../Dataset'
  meta_split_path: '../finetune/data_split'
  
  val_sets:
  ###
    ptbxl_super_class:
      data_path: 'PTB-XL'
      split_path: 'ptbxl/super_class/ptbxl_super_class_val.csv'
  ###
    ptbxl_sub_class:
      data_path: 'PTB-XL'
      split_path: 'ptbxl/sub_class/ptbxl_sub_class_val.csv'
  ###
    ptbxl_form:
      data_path: 'PTB-XL'
      split_path: 'ptbxl/form/ptbxl_form_val.csv'
  ###
    ptbxl_rhythm:
      data_path: 'PTB-XL'
      split_path: 'ptbxl/rhythm/ptbxl_rhythm_val.csv'
  ###
    icbeb:
      data_path: 'icbeb2018/records500'
      split_path: 'icbeb/icbeb_val.csv'
  ###
    chapman:
      data_path: ''
      split_path: 'chapman/chapman_val.csv'

# your model name
wandb_name: 'new_fractal_hard'